!!****if* FlashX_RecipeTools/TimeStepRecipe/_internal_tpl/cg-tpl.TimeAdvance
!!***
!> @copyright Copyright 2023 UChicago Argonne, LLC and contributors
!!
!! @licenseblock
!!   Licensed under the Apache License, Version 2.0 (the "License");
!!   you may not use this file except in compliance with the License.
!!
!!   Unless required by applicable law or agreed to in writing, software
!!   distributed under the License is distributed on an "AS IS" BASIS,
!!   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
!!   See the License for the specific language governing permissions and
!!   limitations under the License.
!! @endlicenseblock
!!


!! Flash-X TimeAdvance unit for Milhoja runtime
!! TimeAdvance.F90 is automatically generated by FlashX_RecipeTools.

#ifdef DEBUG_ALL
#define DEBUG_ADVANCE
#endif

#include "Simulation.h"
#include "constants.h"

subroutine TimeAdvance(dt, dtold, time)

   use iso_c_binding, ONLY : c_ptr, &
                             c_null_ptr

   use Driver_interface, ONLY: Driver_abort
   use Timers_interface, ONLY: Timers_start, Timers_stop

   use Grid_interface, ONLY: Grid_fillGuardCells, &
                             Grid_getTileIterator, &
                             Grid_releaseTileIterator, &
                             Grid_putFluxData, &
                             Grid_getFluxCorrData_block
   use Grid_iterator, ONLY : Grid_iterator_t
   use Grid_tile,     ONLY : Grid_tile_t

   use Orchestration_interfaceTypeDecl, ONLY: Orchestration_tileCInfo_t
   use Orchestration_interface, ONLY: Orchestration_checkInternalError, &
                                      Orchestration_teardownPipeline

   use Milhoja_types_mod, ONLY: MILHOJA_INT, &
                                MILHOJA_SIZE_T, &
                                MILHOJA_REAL
   use milhoja_runtime_mod, ONLY : milhoja_runtime_reset


   !<_link:use_interface>


   implicit none

   real, intent(IN) :: dt, dtold, time

   type(Grid_iterator_t) :: itor
   type(Grid_tile_t)     :: tileDesc
   type(Orchestration_tileCInfo_t) :: cInfo
   integer(MILHOJA_INT) :: MH_ierr
   real, pointer, dimension(:,:,:,:) :: Uin

   integer, dimension(LOW:HIGH, MDIM) :: blkLimits, &
                                         blkLimitsGC, &
                                         grownLimits
   integer, dimension(MDIM) :: lo, loGC, hi, hiGC
   real, dimension(MDIM)  :: deltas

   integer :: stage


   !<_link:var_definition>

   stage = 0                    ! Avoid Warning: 'stage' is used uninitialized - KW

   !<_link:var_initialization>


!!   call Grid_fillGuardCells(CENTER, ALLDIR, doEos=.true.) ! disabled - use cg-tpl.guardcell_fill.F90 instead (or not)


   !<_link:execute>


end subroutine TimeAdvance


